tasker/web/router.ex
defmodule Tasker.Router do
  use Tasker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api/tasks", Tasker.Api do
      pipe_through :api

      get "/", TaskController, :index
      get "/:id", TaskController, :show
      post "/", TaskController, :create
      put "/:id", TaskController, :update
      delete "/:id", TaskController, :delete
      delete "/:id/done", TaskController, :done
      delete "/:id/cancel", TaskController, :cancel


  end

  scope "/api/categories", Tasker.Api do
      pipe_through :api

      get "/", CategoryController, :index
      get "/:id", CategoryController, :show
      post "/", CategoryController, :create
      put "/:id", CategoryController, :update
      delete "/:id", CategoryController, :delete

   end

  scope "/api/stat", Tasker.Api do
      pipe_through :api

      get "/", StatisticsController, :index
  end

  scope "/", Tasker do
    pipe_through :browser # Use the default browser stack
    resources "/categories", CategoryController
    resources "/", TaskController
    delete "/cancel/:id", TaskController, :cancel

  end

  # Other scopes may use custom stacks.
  # scope "/api", Tasker do
  #   pipe_through :api
  # end
end

tasker/web/models/category.ex
defmodule Tasker.Category do
  use Tasker.Web, :model

  schema "categories" do
    field :name, :string
    has_many :task, Tasker.Task, on_delete: :delete_all

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

tasker/web/controllers/api/category_controller.ex
defmodule Tasker.Api.CategoryController do
   use Tasker.Web, :controller
   alias Tasker.Category
   alias Tasker.Commons

   plug :scrub_params, "category" when action in [:create, :update]


   def index(conn, _params) do
       categories = Repo.all(Category)
       render(conn, "index.json", categories: categories)
   end

   def show(conn, %{"id" => id}) do
        category = Repo.get!(Category, id)
        render(conn, "show.json", category: category)
   end

   def create(conn, %{"category" => category_params}) do
         changeset = Category.changeset(%Category{}, category_params)

         case Repo.insert(changeset) do
           {:ok, category} ->
              conn
              |> put_status(:created)
              |> put_resp_header("location", category_path(conn, :show, category))
              |> render("show.json", category: category)
           {:error, changeset} ->
              conn
              |> put_status(:unprocessable_entity)
              |> render("error.json", changeset: Commons.mapErrors(changeset.errors, %{}))
         end
   end

   def update(conn, %{"id" => id, "category" => category_params}) do
         category = Repo.get!(Category, id)
         changeset = Category.changeset(category, category_params)

         case Repo.update(changeset) do
            {:ok, category} ->
                category = Repo.get!(Category, id)
                render(conn, "show.json", category: category)
            {:error, changeset} ->
                conn
                |> put_status(:unprocessable_entity)
                |> render("error.json", changeset: Commons.mapErrors(changeset.errors, %{}))
         end
   end

   def delete(conn, %{"id" => id}) do
         category = Repo.get!(Category, id)
         Repo.delete!(category)
         render(conn, "ok.json")
   end

end

tasker/web/controllers/category_controller.ex
defmodule Tasker.CategoryController do
  use Tasker.Web, :controller

  alias Tasker.Category

  def index(conn, _params) do
    categories = Repo.all(Category)
    render(conn, "index.html", categories: categories)
  end

  def new(conn, _params) do
    changeset = Category.changeset(%Category{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"category_controller.ex" => category_params}) do
    changeset = Category.changeset(%Category{}, category_params)

    case Repo.insert(changeset) do
      {:ok, _category} ->
        conn
        |> put_flash(:info, "Category created successfully.")
        |> redirect(to: category_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    category = Repo.get!(Category, id)
    render(conn, "show.html", category: category)
  end

  def edit(conn, %{"id" => id}) do
    category = Repo.get!(Category, id)
    changeset = Category.changeset(category)
    render(conn, "edit.html", category: category, changeset: changeset)
  end

  def update(conn, %{"id" => id, "category_controller.ex" => category_params}) do
    category = Repo.get!(Category, id)
    changeset = Category.changeset(category, category_params)

    case Repo.update(changeset) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category updated successfully.")
        |> redirect(to: category_path(conn, :show, category))
      {:error, changeset} ->
        render(conn, "edit.html", category: category, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    category = Repo.get!(Category, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(category)

    conn
    |> put_flash(:info, "Category deleted successfully.")
    |> redirect(to: category_path(conn, :index))
  end
end

tasker/web/views/category_view.ex
defmodule Tasker.CategoryView do
  use Tasker.Web, :view
end

tasker/web/templates/category/edit.html.eex
<h2>Edit category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :update, @category) %>

<%= link "Back", to: category_path(@conn, :index) %>

tasker/web/templates/category/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

tasker/web/templates/category/index.html.eex
<h2>Listing categories</h2>

<%= link "Tasks", to: task_path(@conn, :index) %>


<table class="table">
  <thead>
    <tr>
      <th>Id</th>

      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for category <- @categories do %>
    <tr>
      <td><%= category.id %></td>

      <td><%= category.name %></td>

      <td class="text-right">
        <%= link "Show", to: category_path(@conn, :show, category), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: category_path(@conn, :edit, category), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: category_path(@conn, :delete, category), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New category_controller.ex", to: category_path(@conn, :new) %>

tasker/web/templates/category/new.html.eex
<h2>New category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :create) %>

<%= link "Back", to: category_path(@conn, :index) %>

tasker/web/templates/category/show.html.eex
<h2>Show category</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @category.name %>
  </li>

</ul>

<%= link "Edit", to: category_path(@conn, :edit, @category) %>
<br/>
<%= link "Back", to: category_path(@conn, :index) %>